### ISSUE TITLE
Cannot read property tags of null

### ISSUE THREAD

**Issue by kamrankhan54** [leinonen/cucumber-html-report#50]
An error has recently just popped up when generating the html report. This was perfectly working fine.

`TypeError: Cannot read property 'tags' of null
    at parseTags (/node_modules/cucumber-html-report/index.js:77:13)
    at /node_modules/cucumber-html-report/index.js:26:19
    at Array.forEach (native)
    at CucumberHtmlReport.createReport (/node_modules/cucumber-html-report/index.js:25:11)
    at Object.<anonymous> (/test/dist/src/createReport.js:29:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)`

**Comment by leinonen** [comment]
Can you try the latest version? Re-open issue if you still experience problems.
