### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by sreedharputtgunta** [leinonen/cucumber-html-report#57]
Getting the following error with the latest version
ReferenceError: Promise is not defined
at templateBuilder.init (.../node_modules/cucumber-html-report/builder/template_builder.js:54:20)
at Object.<anonymous> (.../node_modules/cucumber-html-report/index.js:40:10)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at [eval]:1:6

we use the package in the following way

npm install cucumber-html-report
node -e "new (require('cucumber-html-report'))({source: './build/reports/cucumber/cucumber.json',dest: './build/reports',name: 'BuildReport.html',title: 'Test Results'}).createReport();"

Please let me know if there is anything that we are missing or this is something which needs to be fixed in your code

**Comment by leinonen** [comment]
Working on it. Use old version for now

Den ons 25 jan. 2017 04:20Sreedhar Puttagunta <notifications@github.com>
skrev:

**Comment by leinonen** [comment]
Please test version 0.5.0

**Comment by leinonen** [comment]
Try latest release.
