### ISSUE TITLE
Default logo not working?

### ISSUE THREAD

**Issue by leinonen** [leinonen/cucumber-html-report#60]

**Comment by aluzardo** [comment]
Maybe this could help:

In my case, I am getting this error:
```
{ Error: ENOENT: no such file or directory, open './logos/cucumber-logo.svg'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at getDataUri (/Users/adolfocabrera/Mavrix/protractor-cucumber-tests/node_modules/cucumber-html-report/lib/report.js:199:19)
    at encodeLogo (/Users/adolfocabrera/Mavrix/protractor-cucumber-tests/node_modules/cucumber-html-report/lib/report.js:493:51)
    at exports.createReport (/Users/adolfocabrera/Mavrix/protractor-cucumber-tests/node_modules/cucumber-html-report/lib/report.js:172:11)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './logos/cucumber-logo.svg' }
```
The problem is that is looking for `cucumber-logo.svg` in a wrong path.

I fixed using this:
```     var report = require('cucumber-html-report');
        report.create({
            source: sourceJson,
            dest: outputDir,
            name: name,
            logo: 'node_modules/cucumber-html-report/logos/cucumber-logo.svg'
        }).then(console.log).catch(console.error);
```

**Comment by leinonen** [comment]
Thanks, I'll look into it asap :)

**Comment by leinonen** [comment]
Hello, can you please test version 0.5.1 ?

**Comment by aluzardo** [comment]
Tested and fixed. 🔧 

You are the man! 🎉
