### ISSUE TITLE
Showing error, but report successfully generated

### ISSUE THREAD

**Issue by 77ganesh** [leinonen/cucumber-html-report#66]
Hi, I am getting the following error, but the report is being sucessfully generated.

[16:15:48] Using gulpfile P:\xmt-auto-cucumber\gulpfile.js
[16:15:48] Starting 'report'...
Directory already exists: ./reports
[16:16:19] 'report' errored after 31 s
[16:16:19] Error: Report created successfully!
    at formatError (C:\Users\a566028\AppData\Roaming\npm\node_modules\gulp-cli\
ib\versioned\^4.0.0\formatError.js:20:10)
    at Gulp.<anonymous> (C:\Users\a566028\AppData\Roaming\npm\node_modules\gulp
cli\lib\versioned\^4.0.0\log\events.js:30:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Object.error (P:\xmt-auto-cucumber\node_modules\undertaker\lib\helpers\c
eateExtensions.js:61:10)
    at handler (P:\xmt-auto-cucumber\node_modules\now-and-later\lib\map.js:46:1
)
    at f (P:\xmt-auto-cucumber\node_modules\once\once.js:25:25)
    at f (P:\xmt-auto-cucumber\node_modules\once\once.js:25:25)
    at done (P:\xmt-auto-cucumber\node_modules\async-done\index.js:24:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by leinonen** [comment]
Hm, will investigate..
