### ISSUE TITLE
Would it possible to use this with protrcator cuucmber framework ?

### ISSUE THREAD

**Issue by pnakhat** [leinonen/cucumber-html-report#71]
Hi I use https://github.com/protractor-cucumber-framework/protractor-cucumber-framework. Is it possible to use this plugin with this framework. I use chai for assertions ?

**Comment by leinonen** [comment]
Yes it is, that is what I use it for.

Den ons 24 maj 2017 10:05pnakhat <notifications@github.com> skrev:

**Comment by pnakhat** [comment]
some reason doesn't work in mine project this is my config 

`var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

exports.config = {
    // set to "custom" instead of cucumber.

    onPrepare: function() {
        // Add a screenshot reporter and store screenshots to `/tmp/screnshots`:
        browser.ignoreSynchronization = true;
        browser.manage().timeouts().pageLoadTimeout(40000);
        browser.manage().timeouts().implicitlyWait(25000);



        jasmine.getEnv().addReporter(new ScreenShotReporter({
            baseDirectory: '/tmp/screenshots'
        }));
    },

    framework: 'custom',
    directConnect: false,
    seleniumAddress: 'http://localhost:4444/wd/hub',
    baseUrl: 'http://www.google.com',
    ignoreUncaughtExceptions: true,

// resultJsonOutputFile: 'report/report2.json',

    capabilities: {
        'browserName': (process.env.TEST_BROWSER_NAME || 'chrome'),
        // 'chromeOptions': {
        //     // Prevent warning about dev tools, which breaks some tests, in Windows at least.
        //     'args': ['--disable-extensions']
        // },

        // 'version': (process.env.TEST_BROWSER_VERSION || 'ANY'),
        'marionette': true
    },

    // path relative to the current config file
    frameworkPath: require.resolve('protractor-cucumber-framework'),

    // require feature files
    specs: [
        'features/log*.feature' // accepts a glob
    ],

    onPrepare: function () {

        browser.ignoreSynchronization = true;
        browser.manage().window().maximize();
        global.expect = chai.expect;
    },

    cucumberOpts: {
        // require step definitions
        strict: true,
        format: 'json:report/json/report.json',
        require: [
            'features/step_definitions/*.js' // accepts a glob
        ]
    }
};`

**Comment by EugeneSnihovsky** [comment]
Hi.
Thanks for great tool. I have same question.
I use `cucumber@2.2.0` and `protractor-cucumber-framework@3.1.0`

My `protractor.conf.js` settings

```
    resultJsonOutputFile: 'reports/report.json',
    cucumberOpts: {
        require: [
            './features/step_definitions/**/*_steps.ts'
        ],
        monochrome: false,
        format: [
            'pretty'
        ],
        compiler: "ts:ts-node/register",
        'fail-fast': true
    }
```

My gulp task for report creation

```
const report = require('cucumber-html-report');

gulp.task('html-report', () => {
  report.create({
    source: './reports/report.json',
    dest: './reports',
    name: 'report.html'
  })
      .then(console.log)
      .catch(console.error);
});
```

My report.json generated by tests

```json

[
  {
    "description": "Show error during sign in with wrong credentials",
    "assertions": [
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      }
    ],
    "events": [
      {
        "emitterEvent": "testPass",
        "name": "When I go to \"sign in\" page",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials",
        "durationMillis": 578,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 6,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "And I fill \"username\" input field with \"alex.a1.at@agiliumlabs.com\"",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials",
        "durationMillis": 838,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 7,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "And I fill \"password\" input field with \"wrongPassword\"",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials",
        "durationMillis": 151,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 8,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "And I click \"log in\" button",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials",
        "durationMillis": 52,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 9,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "Then I should see \"Wrong credentials\" error notification",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials",
        "durationMillis": 2536,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 10,
          "column": 1
        }
      }
    ],
    "duration": 4155
  },
  {
    "description": "Show error during sign in with wrong credentials 2",
    "assertions": [
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      },
      {
        "passed": true
      }
    ],
    "events": [
      {
        "emitterEvent": "testPass",
        "name": "When I go to \"sign in\" page",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials 2",
        "durationMillis": 413,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 14,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "And I fill \"username\" input field with \"alex.a1.at@agiliumlabs.com\"",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials 2",
        "durationMillis": 135,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 15,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "And I fill \"password\" input field with \"wrongPassword\"",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials 2",
        "durationMillis": 111,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 16,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "And I click \"log in\" button",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials 2",
        "durationMillis": 44,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 17,
          "column": 1
        }
      },
      {
        "emitterEvent": "testPass",
        "name": "Then I should see \"Wrong credentials\" error notification",
        "category": "Sign in page scenario: Show error during sign in with wrong credentials 2",
        "durationMillis": 1546,
        "sourceLocation": {
          "filePath": "/Volumes/WORKSPACE/projects/tracker-agent-v3/features/sign-in/sign-in.feature",
          "line": 18,
          "column": 1
        }
      }
    ],
    "duration": 2249
  }
]
```

When I try to create html report with gulp task I receive an error

```bash
TypeError: Array.prototype.slice called on null or undefined
    at sortWith (/Volumes/WORKSPACE/projects/tracker-agent-v3/node_modules/ramda/src/sortWith.js:37:32)
    at Object.f2 [as sortWith] (/Volumes/WORKSPACE/projects/tracker-agent-v3/node_modules/ramda/src/internal/_curry2.js:25:16)
    at sortByStatusAndName (/Volumes/WORKSPACE/projects/tracker-agent-v3/node_modules/cucumber-html-report/lib/report.js:273:12)
    at sortScenariosForFeature (/Volumes/WORKSPACE/projects/tracker-agent-v3/node_modules/cucumber-html-report/lib/report.js:277:22)
    at Array.map (native)
    at parseFeatures (/Volumes/WORKSPACE/projects/tracker-agent-v3/node_modules/cucumber-html-report/lib/report.js:282:107)
    at exports.createReport (/Volumes/WORKSPACE/projects/tracker-agent-v3/node_modules/cucumber-html-report/lib/report.js:78:18)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
```

Maybe I missed something?

**Comment by leinonen** [comment]
The format looks wrong. Try the following and let me know if it helps:
```json
  cucumberOpts: {
    format: 'json:results.json',
    // ...
  }
```

**Comment by leinonen** [comment]
I use it in the following way:

```javascript
// hooks.js
const cucumber = require('cucumber');
const report = require('cucumber-html-report');

module.exports = function () {
  const formatter = cucumber.Listener.JsonFormatter();
  formatter.log = (data) => {
    fs.writeFile('report.json', data, (err) => {
      if (err) {
        console.log('Failed to save cucumber test results to json file.', err); // eslint-disable-line no-console
      } else {
        report.create({
          component: 'MyComponent',
          source: 'report.json',
          dest: './report',
        }).then(console.log).catch(console.log);
      }
    });
  };
  this.registerListener(formatter);
};
````

**Comment by EugeneSnihovsky** [comment]
Yes, you are right. When I changed `cucumberOpts.format` to `['json:reports/results.json', 'pretty']` - new file `results.json` with correct format created and all works fine. Thanks.
